
import type { Product } from '@/types';
import type { Timestamp } from 'firebase/firestore';

// This file (initialProductsData) is now primarily for reference or seeding purposes.
// The application fetches product data directly from Firestore.
// The admin panel manages products in the `/products` collection in Firestore.

// If you need to manually add products to Firestore for testing, 
// you can adapt the structure below. Make sure 'createdAt' and 'updatedAt'
// are Firestore Timestamps. 'id' will be auto-generated by Firestore.

export const initialProductsData_DEPRECATED: Omit<Product, 'id' | 'createdAt' | 'updatedAt' | 'description'>[] & { description: string }[] = [
  {
    brand: 'CoolWave',
    model: 'X2000',
    price: 25000,
    capacity: '1.5 Ton',
    // warranty field removed from Product type, managed in description or features if needed
    imageUrl: 'https://placehold.co/400x300.png',
    features: 'Inverter Technology, Smart Controls, Air Purification',
    condition: 'Used',
    stock: 10,
    category: 'Split AC',
    description: 'This is a Used CoolWave X2000 AC unit with a 1.5 Ton capacity. Key features include: Inverter Technology, Smart Controls, Air Purification. It comes with a standard seller warranty. An excellent choice for reliable cooling.',
  },
  {
    brand: 'ArcticBlast',
    model: 'ProSilent',
    price: 18000,
    capacity: '1.0 Ton',
    imageUrl: 'https://placehold.co/400x300.png',
    features: 'Quiet Operation, Energy Saver, Turbo Cool',
    condition: 'Used',
    stock: 5,
    category: 'Window AC',
    description: 'Introducing the Used ArcticBlast ProSilent, a 1.0 Ton AC unit. Notable features are: Quiet Operation, Energy Saver, Turbo Cool. This unit includes a seller warranty. Perfect for efficient and silent cooling.',
  },
  {
    brand: 'FrostFlow',
    model: 'EcoSmart',
    price: 32000,
    capacity: '2.0 Ton',
    imageUrl: 'https://placehold.co/400x300.png',
    features: 'Eco Mode, Wi-Fi Enabled, Dehumidifier',
    condition: 'New',
    stock: 15,
    category: 'Split AC',
    description: 'Explore the New FrostFlow EcoSmart, a powerful 2.0 Ton AC. It boasts features like: Eco Mode, Wi-Fi Enabled, Dehumidifier, and comes with a manufacturer warranty. Ideal for larger spaces requiring smart cooling.',
  },
   {
    brand: 'ChillMaster',
    model: 'CompactCool',
    price: 15000,
    capacity: '0.8 Ton',
    imageUrl: 'https://placehold.co/400x300.png',
    features: 'Portable, Easy Install, Remote Control',
    condition: 'Used',
    stock: 0, // Example of an out-of-stock item
    category: 'Portable AC',
    description: 'Check out the Used ChillMaster CompactCool, a 0.8 Ton AC unit. Its main features are: Portable, Easy Install, Remote Control. It is covered by a seller warranty. A great portable solution for personal cooling.',
  },
];

// Example of how you might structure product data for Firestore:
// {
//   brand: "ExampleBrand",
//   model: "ExampleModel",
//   price: 20000, // number
//   capacity: "1.2 Ton",
//   stock: 5, // number
//   condition: "New", // "New" or "Used"
//   imageUrl: "https://placehold.co/600x400.png",
//   description: "A detailed description of the product.",
//   category: "Split AC",
//   features: "Feature1, Feature2, Feature3", // optional
//   createdAt: serverTimestamp(), // Firestore server timestamp
//   updatedAt: serverTimestamp(), // Firestore server timestamp
// }
